export default [
  {
    id: "1",
    name: "Grupa A",
    color: "primary",
    members: [
      {
        id: "1",
        firstName: "Ivan",
        lastName: "Horvat",
        avatar: "IH",
        groupRanking: 3,
      },
      {
        id: "2",
        firstName: "Ana",
        lastName: "Kovačić",
        avatar: "AK",
        groupRanking: 2,
      },
      {
        id: "3",
        firstName: "Petar",
        lastName: "Babić",
        avatar: "PB",
        groupRanking: 1,
      },
      {
        id: "4",
        firstName: "Marija",
        lastName: "Marić",
        avatar: "MM",
        groupRanking: 4,
      },
    ],
  },
  {
    id: "2",
    name: "Grupa B",
    color: "secondary",
    members: [
      {
        id: "5",
        firstName: "Luka",
        lastName: "Novak",
        avatar: "LN",
        groupRanking: 1,
      },
      {
        id: "6",
        firstName: "Ivana",
        lastName: "Jurić",
        avatar: "IJ",
        groupRanking: 4,
      },
      {
        id: "7",
        firstName: "Tomislav",
        lastName: "Šarić",
        avatar: "TŠ",
        groupRanking: 2,
      },
      {
        id: "8",
        firstName: "Katarina",
        lastName: "Božić",
        avatar: "KB",
        groupRanking: 3,
      },
    ],
  },
  {
    id: "3",
    name: "Grupa C",
    color: "success",
    members: [
      {
        id: "9",
        firstName: "Marko",
        lastName: "Knežević",
        avatar: "MK",
        groupRanking: 2,
      },
      {
        id: "10",
        firstName: "Martina",
        lastName: "Pavić",
        avatar: "MP",
        groupRanking: 1,
      },
      {
        id: "11",
        firstName: "Josip",
        lastName: "Grgić",
        avatar: "JG",
        groupRanking: 4,
      },
      {
        id: "12",
        firstName: "Maja",
        lastName: "Filipović",
        avatar: "MF",
        groupRanking: 3,
      },
    ],
  },
  {
    id: "4",
    name: "Grupa D",
    color: "warning",
    members: [
      {
        id: "13",
        firstName: "Stjepan",
        lastName: "Perić",
        avatar: "SP",
        groupRanking: 3,
      },
      {
        id: "14",
        firstName: "Lucija",
        lastName: "Radić",
        avatar: "LR",
        groupRanking: 2,
      },
      {
        id: "15",
        firstName: "Dario",
        lastName: "Tomić",
        avatar: "DT",
        groupRanking: 4,
      },
      {
        id: "16",
        firstName: "Sara",
        lastName: "Lovrić",
        avatar: "SL",
        groupRanking: 1,
      },
    ],
  },
  {
    id: "5",
    name: "Grupa E",
    color: "error",
    members: [
      {
        id: "17",
        firstName: "Krešimir",
        lastName: "Živković",
        avatar: "KŽ",
        groupRanking: 4,
      },
      {
        id: "18",
        firstName: "Tena",
        lastName: "Matić",
        avatar: "TM",
        groupRanking: 2,
      },
      {
        id: "19",
        firstName: "Ante",
        lastName: "Petrić",
        avatar: "AP",
        groupRanking: 3,
      },
      {
        id: "20",
        firstName: "Lea",
        lastName: "Vidović",
        avatar: "LV",
        groupRanking: 1,
      },
    ],
  },
  {
    id: "6",
    name: "Grupa F",
    color: "info",
    members: [
      {
        id: "21",
        firstName: "Filip",
        lastName: "Jakovljević",
        avatar: "FJ",
        groupRanking: 2,
      },
      {
        id: "22",
        firstName: "Helena",
        lastName: "Rukavina",
        avatar: "HR",
        groupRanking: 3,
      },
      {
        id: "23",
        firstName: "Zvonimir",
        lastName: "Ljubić",
        avatar: "ZL",
        groupRanking: 4,
      },
      {
        id: "24",
        firstName: "Iva",
        lastName: "Pranjić",
        avatar: "IP",
        groupRanking: 1,
      },
    ],
  },
  {
    id: "7",
    name: "Grupa G",
    color: "default",
    members: [
      {
        id: "25",
        firstName: "Mario",
        lastName: "Vuković",
        avatar: "MV",
        groupRanking: 3,
      },
      {
        id: "26",
        firstName: "Diana",
        lastName: "Miljković",
        avatar: "DM",
        groupRanking: 2,
      },
      {
        id: "27",
        firstName: "Hrvoje",
        lastName: "Barišić",
        avatar: "HB",
        groupRanking: 4,
      },
      {
        id: "28",
        firstName: "Nina",
        lastName: "Krpan",
        avatar: "NK",
        groupRanking: 1,
      },
    ],
  },
  {
    id: "8",
    name: "Grupa H",
    color: "primary",
    members: [
      {
        id: "29",
        firstName: "Domagoj",
        lastName: "Glavaš",
        avatar: "DG",
        groupRanking: 4,
      },
      {
        id: "30",
        firstName: "Paula",
        lastName: "Klarić",
        avatar: "PK",
        groupRanking: 2,
      },
      {
        id: "31",
        firstName: "Matej",
        lastName: "Obradović",
        avatar: "MO",
        groupRanking: 1,
      },
      {
        id: "32",
        firstName: "Ema",
        lastName: "Čović",
        avatar: "EČ",
        groupRanking: 3,
      },
    ],
  },
];
