export default [
  {
    firstName: "Marko",
    lastName: "Bošković",
    email: "marko.boskovic@marko.boskovic.com",
    password: "markobošković123",
    firebaseId: "0QeiGLftDWSGhb3rye4lO7Gmvsr2",
    phone: "+385997860126",
  },
  {
    firstName: "Igor",
    lastName: "Mijatov",
    email: "igor.mijatov@igor.mijatov.com",
    password: "igormijatov123",
    firebaseId: "0YAJLuHDB5VP66rd3D2zWDOmMUA3",
    phone: "+38598329984",
  },
  {
    firstName: "Filip",
    lastName: "Čevizović",
    email: "filip.cevizovic@filip.cevizovic.com",
    password: "filipčevizović123",
    firebaseId: "61ySx2tIK2aDMS5CnCCpc1exwou2",
    phone: "+385989784916",
  },
  {
    firstName: "Vedran",
    lastName: "Cerina",
    email: "vedran.cerina@vedran.cerina.com",
    password: "vedrancerina123",
    firebaseId: "8VZYwhTifqg6C4JDuFjcMLjNxp62",
    phone: "+385959156546",
  },
  {
    firstName: "Patrick",
    lastName: "Nikić",
    email: "patrick.nikic@patrick.nikic.com",
    password: "patricknikić123",
    firebaseId: "9cMJ5qlhovaSAjA1Rdp1wUdqrBJ2",
    phone: "+385997728631",
  },
  {
    firstName: "Davor",
    lastName: "Grgić",
    email: "davor.grgic@davor.grgic.com",
    password: "davorgrgić123",
    firebaseId: "Bgiv8elIYNaQV16gmNlQDWPl4vj1",
    phone: "+385913454557",
  },
  {
    firstName: "Marko",
    lastName: "Jović",
    email: "marko.jovic@marko.jovic.com",
    password: "markojović123",
    firebaseId: "KgwTrqmSqROmSkWfc7FePW3hOjm1",
    phone: "+385989003751",
  },
  {
    firstName: "Mario",
    lastName: "Štrok",
    email: "mario.strok@mario.strok.com",
    password: "marioštrok123",
    firebaseId: "NXLnCygXELOrLExtDDL9xsqqHxs2",
    phone: "+385989767070",
  },
  {
    firstName: "Mario",
    lastName: "Jerković",
    email: "mario.jerkovic@mario.jerkovic.com",
    password: "mariojerković123",
    firebaseId: "NdDjMc2IrcbKWOAh8hj3ysvIduD3",
    phone: "+385992374324",
  },
  {
    firstName: "Ivan",
    lastName: "Župan",
    email: "ivan.zupan@ivan.zupan.com",
    password: "ivanžupan123",
    firebaseId: "PackjJmJO1PPIAumxoZR0xV0iKk2",
    phone: "+385955320245",
  },
  {
    firstName: "Ivan",
    lastName: "Lazić",
    email: "ivan.lazic@ivan.lazic.com",
    password: "ivanlazić123",
    firebaseId: "RlOpTqaqVvUbmIx6biljzpmsfM23",
    phone: "+385992616800",
  },
  {
    firstName: "Domagoj",
    lastName: "Roguljić",
    email: "domagoj.roguljic@domagoj.roguljic.com",
    password: "domagojroguljić123",
    firebaseId: "Tdv8C8b6Q5ZJTEDxqfdRlHAUj6L2",
    phone: "+385917929744",
  },
  {
    firstName: "Dario",
    lastName: "Jagarinec",
    email: "dario.jagarinec@dario.jagarinec.com",
    password: "dariojagarinec123",
    firebaseId: "Te3EsR4ladMEnOkR65CIQ6X2Oah2",
    phone: "+38598223333",
  },
  {
    firstName: "Ivan",
    lastName: "Ambreuš",
    email: "ivan.ambres@ivan.ambres.com",
    password: "ivanambreuš123",
    firebaseId: "WMuGrVVIJfYb8rdj4GxLIvh8kBh2",
    phone: "+385958186967",
  },
  {
    firstName: "Robert",
    lastName: "Švab",
    email: "robert.svab@robert.svab.com",
    password: "robertšvab123",
    firebaseId: "XHKuOIhDiRYIu1zFUbMdNXNECPG3",
    phone: "+385916400219",
  },
  {
    firstName: "Angela",
    lastName: "Di Roma",
    email: "angela.diroma@angela.diroma.com",
    password: "angeladiroma123",
    firebaseId: "XgqxD2zw15gI8fROqj6xPQ1b2ux1",
    phone: "+491735133688",
  },
  {
    firstName: "Matko",
    lastName: "Vicić",
    email: "matko.vicic@matko.vicic.com",
    password: "matkovicić123",
    firebaseId: "YOrrIrvpooVWCRWX9gzs5EjLCD43",
    phone: "+385913093065",
  },
  {
    firstName: "Dinko",
    lastName: "Pleša",
    email: "dinko.plesa@dinko.plesa.com",
    password: "dinkopleša123",
    firebaseId: "bNCsSiOW0teYIFRuxXC4SELij3Z2",
    phone: "+385915661258",
  },
  {
    firstName: "Željko",
    lastName: "Bilić",
    email: "zeljko.bilic@zeljko.bilic.com",
    password: "željkobilić123",
    firebaseId: "bSP0oL0zRPZnwLrPTWD1qR6uQzv1",
    phone: "+38598315979",
  },
  {
    firstName: "Danijel",
    lastName: "Jakovac",
    email: "danijel.jakovac@danijel.jakovac.com",
    password: "danijeljakovac123",
    firebaseId: "ciuWwLPeorZ69cbXfDWvTTICM6P2",
    phone: "+385953533072",
  },
  {
    firstName: "Tihomir",
    lastName: "Šimunić",
    email: "tihomir.simunic@tihomir.simunic.com",
    password: "tihomiršimunić123",
    firebaseId: "dBYcjePClXUYZHAMbCVbtoH7dSL2",
    phone: "+385916223202",
  },
  {
    firstName: "Antun",
    lastName: "Marošević",
    email: "antun.marosevic@antun.marosevic.com",
    password: "antunmarošević123",
    firebaseId: "g3n98fHe82f26hXfXIxFg9Wuv9k1",
    phone: "+385916191737",
  },
  {
    firstName: "Bruno",
    lastName: "Jagarinec",
    email: "bruno.jagarinec@bruno.jagarinec.com",
    password: "brunojagarinec123",
    firebaseId: "jez4lbWbtMcFzHaaC4lZqX0dgEz1",
    phone: "+385915775732",
  },
  {
    firstName: "Damjan",
    lastName: "Simonović",
    email: "damjan.simonovic@damjan.simonovic.com",
    password: "damjansimonović123",
    firebaseId: "jzbWUnrsEqNKXJ6rEVTuSXrlDLo2",
    phone: "+385994876499",
  },
  {
    firstName: "Matej",
    lastName: "Tolj",
    email: "matej.tolj@matej.tolj.com",
    password: "matejtolj123",
    firebaseId: "k71IlIxZjNU9IYmoK7WgJPe8WcW2",
    phone: "+385951977137",
  },
  {
    firstName: "Vicko",
    lastName: "Mustapić",
    email: "vicko.mustapic@vicko.mustapic.com",
    password: "vickomustapić123",
    firebaseId: "laSQqPrCOGNQAkwhIigNsNdAG4D2",
    phone: "+38598825180",
  },
  {
    firstName: "Ivan",
    lastName: "Tolić",
    email: "ivan.tolic@ivan.tolic.com",
    password: "ivantolić123",
    firebaseId: "oqANEgkBfob6l0pocroQMTdbR5r1",
    phone: "+385989130323",
  },
  {
    firstName: "Ivan",
    lastName: "Kožul",
    email: "ivan.kozul@ivan.kozul.com",
    password: "ivankožul123",
    firebaseId: "pqpZKupNWVgPsXeqm7cNm9KX69G3",
    phone: "+385989615495",
  },
  {
    firstName: "Antun",
    lastName: "Rukavina",
    email: "antun.rukavina@antun.rukavina.com",
    password: "antunrukavina123",
    firebaseId: "qjoXNj7h3XMaqshxiRDuH3KJsxG3",
    phone: "+385997804794",
  },
  {
    firstName: "Krešimir",
    lastName: "Lončarević",
    email: "kresimir.loncarevic@kresimir.loncarevic.com",
    password: "krešimirlončarević123",
    firebaseId: "uQU4tEsYEeSdt6n2xHLXZkngrex1",
    phone: "+385993234994",
  },
  {
    firstName: "Boris",
    lastName: "Tanasić",
    email: "boris.tanasic@boris.tanasic.com",
    password: "boristanasić123",
    firebaseId: "wWP3cINFXSRptkwXPsL394GTS1q1",
    phone: "+385989569695",
  },
  {
    firstName: "Domagoj",
    lastName: "Vidaković",
    email: "domagoj.vidakovic@domagoj.vidakovic.com",
    password: "domagojvidaković123",
    firebaseId: "wfqmXUC9htZkEyUOo3s5K8d0w9G2",
    phone: "+385955664412",
  },
  {
    firstName: "Ivan",
    lastName: "Zubac",
    email: "ivan.zubac@ivan.zubac.com",
    password: "ivanzubac123",
    firebaseId: "zeyEuOP4Nbhs20UORQhzVzfC1hd2",
    phone: "+385915858646",
  },
];
