export const players = [
  {
    firstName: "Marko",
    lastName: "Jović",
    phone: "+385989003751",
    email: "markojović@markojović",
    password: "markojović123",
  },
  {
    firstName: "Antun",
    lastName: "Rukavina",
    phone: "+385997804794",
    email: "antunrukavina@antunrukavina",
    password: "antunrukavina123",
  },
  {
    firstName: "Domagoj",
    lastName: "Vidaković",
    phone: "+385955664412",
    email: "domagojvidaković@domagojvidaković",
    password: "domagojvidaković123",
  },
  {
    firstName: "Mario",
    lastName: "Jerković",
    phone: "+385992374324",
    email: "mariojerković@mariojerković",
    password: "mariojerković123",
  },
  {
    firstName: "Ivan",
    lastName: "Lazić",
    phone: "+385992616800",
    email: "ivanlazić@ivanlazić",
    password: "ivanlazić123",
  },
  {
    firstName: "Marko",
    lastName: "Bošković",
    phone: "+385997860126",
    email: "markobošković@markobošković",
    password: "markobošković123",
  },
  {
    firstName: "Igor",
    lastName: "Mijatov",
    phone: "+38598329984",
    email: "igormijatov@igormijatov",
    password: "igormijatov123",
  },
  {
    firstName: "Dinko",
    lastName: "Pleša",
    phone: "+385915661258",
    email: "dinkopleša@dinkopleša",
    password: "dinkopleša123",
  },
  {
    firstName: "Filip",
    lastName: "Čevizović",
    phone: "+385989784916",
    email: "filipčevizović@filipčevizović",
    password: "filipčevizović123",
  },
  {
    firstName: "Damjan",
    lastName: "Simonović",
    phone: "+385994876499",
    email: "damjansimonović@damjansimonović",
    password: "damjansimonović123",
  },
  {
    firstName: "Krešimir",
    lastName: "Lončarević",
    phone: "+385993234994",
    email: "krešimirlončarević@krešimirlončarević",
    password: "krešimirlončarević123",
  },
  {
    firstName: "Robert",
    lastName: "Švab",
    phone: "+385916400219",
    email: "robertšvab@robertšvab",
    password: "robertšvab123",
  },
  {
    firstName: "Danijel",
    lastName: "Jakovac",
    phone: "+385953533072",
    email: "danijeljakovac@danijeljakovac",
    password: "danijeljakovac123",
  },
  {
    firstName: "Patrick",
    lastName: "Nikić",
    phone: "+385997728631",
    email: "patricknikić@patricknikić",
    password: "patricknikić123",
  },
  {
    firstName: "Željko",
    lastName: "Bilić",
    phone: "+38598315979",
    email: "željkobilić@željkobilić",
    password: "željkobilić123",
  },
  {
    firstName: "Ivan",
    lastName: "Kožul",
    phone: "+385989615495",
    email: "ivankožul@ivankožul",
    password: "ivankožul123",
  },
  {
    firstName: "Hrvoje",
    lastName: "Grubeša",
    phone: "+385994177878",
    email: "hrvojegrubeša@hrvojegrubeša",
    password: "hrvojegrubeša123",
  },
  {
    firstName: "Ivan",
    lastName: "Tolić",
    phone: "+385989130323",
    email: "ivantolić@ivantolić",
    password: "ivantolić123",
  },
  {
    firstName: "Matej",
    lastName: "Tolj",
    phone: "+385951977137",
    email: "matejtolj@matejtolj",
    password: "matejtolj123",
  },
  {
    firstName: "Tihomir",
    lastName: "Šimunić",
    phone: "+385916223202",
    email: "tihomiršimunić@tihomiršimunić",
    password: "tihomiršimunić123",
  },
  {
    firstName: "Mario",
    lastName: "Kralj",
    phone: "+385976594144",
    email: "mariokralj@mariokralj",
    password: "mariokralj123",
  },
  {
    firstName: "Vedran",
    lastName: "Cerina",
    phone: "+385959156546",
    email: "vedrancerina@vedrancerina",
    password: "vedrancerina123",
  },
  {
    firstName: "Ivan",
    lastName: "Vrebac",
    phone: "+385912341110",
    email: "ivanvrebac@ivanvrebac",
    password: "ivanvrebac123",
  },
  {
    firstName: "Ivan",
    lastName: "Župan",
    phone: "+385955320245",
    email: "ivanžupan@ivanžupan",
    password: "ivanžupan123",
  },
  {
    firstName: "Vicko",
    lastName: "Mustapić",
    phone: "+38598825180",
    email: "vickomustapić@vickomustapić",
    password: "vickomustapić123",
  },
  {
    firstName: "Nenad",
    lastName: "Cvijetić",
    phone: "+385915619888",
    email: "nenadcvijetić@nenadcvijetić",
    password: "nenadcvijetić123",
  },
  {
    firstName: "Matko",
    lastName: "Vicić",
    phone: "+385913093065",
    email: "matkovicić@matkovicić",
    password: "matkovicić123",
  },
  {
    firstName: "Angela",
    lastName: "Di Roma",
    phone: "+491735133688",
    email: "angeladiroma@angeladiroma",
    password: "angeladiroma123",
  },
  {
    firstName: "Slavko",
    lastName: "Nedić",
    phone: "+385913512001",
    email: "slavkonedić@slavkonedić",
    password: "slavkonedić123",
  },
  {
    firstName: "Dražen",
    lastName: "Medvedec",
    phone: "+385998862571",
    email: "draženmedvedec@draženmedvedec",
    password: "draženmedvedec123",
  },
  {
    firstName: "Bruno",
    lastName: "Jagarinec",
    phone: "+385915775732",
    email: "brunojagarinec@brunojagarinec",
    password: "brunojagarinec123",
  },
  {
    firstName: "Mario",
    lastName: "Štrok",
    phone: "+385989767070",
    email: "marioštrok@marioštrok",
    password: "marioštrok123",
  },
];
