export const playersData = [
  {
    id: 1,
    firstName: "Ivan",
    lastName: "Horvat",
    phone: "+385 91 123 4567",
    email: "ivan.horvat@email.com",
  },
  {
    id: 2,
    firstName: "Ana",
    lastName: "Kovačić",
    phone: "+385 98 234 5678",
    email: "ana.kovacic@email.com",
  },
  {
    id: 3,
    firstName: "Petar",
    lastName: "Babić",
    phone: "+385 95 345 6789",
    email: "petar.babic@email.com",
  },
  {
    id: 4,
    firstName: "Marija",
    lastName: "Marić",
    phone: "+385 92 456 7890",
    email: "marija.maric@email.com",
  },
  {
    id: 5,
    firstName: "Luka",
    lastName: "Novak",
    phone: "+385 97 567 8901",
    email: "luka.novak@email.com",
  },
  {
    id: 6,
    firstName: "Ivana",
    lastName: "Jurić",
    phone: "+385 99 678 9012",
    email: "ivana.juric@email.com",
  },
  {
    id: 7,
    firstName: "Tomislav",
    lastName: "Šarić",
    phone: "+385 91 789 0123",
    email: "tomislav.saric@email.com",
  },
  {
    id: 8,
    firstName: "Katarina",
    lastName: "Božić",
    phone: "+385 98 890 1234",
    email: "katarina.bozic@email.com",
  },
  {
    id: 9,
    firstName: "Marko",
    lastName: "Knežević",
    phone: "+385 95 901 2345",
    email: "marko.knezevic@email.com",
  },
  {
    id: 10,
    firstName: "Martina",
    lastName: "Pavić",
    phone: "+385 92 012 3456",
    email: "martina.pavic@email.com",
  },
  {
    id: 11,
    firstName: "Josip",
    lastName: "Grgić",
    phone: "+385 97 111 2233",
    email: "josip.grgic@email.com",
  },
  {
    id: 12,
    firstName: "Maja",
    lastName: "Filipović",
    phone: "+385 99 222 3344",
    email: "maja.filipovic@email.com",
  },
  {
    id: 13,
    firstName: "Stjepan",
    lastName: "Perić",
    phone: "+385 91 333 4455",
    email: "stjepan.peric@email.com",
  },
  {
    id: 14,
    firstName: "Lucija",
    lastName: "Radić",
    phone: "+385 98 444 5566",
    email: "lucija.radic@email.com",
  },
  {
    id: 15,
    firstName: "Dario",
    lastName: "Tomić",
    phone: "+385 95 555 6677",
    email: "dario.tomic@email.com",
  },
  {
    id: 16,
    firstName: "Sara",
    lastName: "Lovrić",
    phone: "+385 92 666 7788",
    email: "sara.lovric@email.com",
  },
  {
    id: 17,
    firstName: "Krešimir",
    lastName: "Živković",
    phone: "+385 97 777 8899",
    email: "kresimir.zivkovic@email.com",
  },
  {
    id: 18,
    firstName: "Tena",
    lastName: "Matić",
    phone: "+385 99 888 9900",
    email: "tena.matic@email.com",
  },
  {
    id: 19,
    firstName: "Ante",
    lastName: "Petrić",
    phone: "+385 91 101 2020",
    email: "ante.petric@email.com",
  },
  {
    id: 20,
    firstName: "Lea",
    lastName: "Vidović",
    phone: "+385 98 202 3030",
    email: "lea.vidovic@email.com",
  },
  {
    id: 21,
    firstName: "Filip",
    lastName: "Jakovljević",
    phone: "+385 95 303 4040",
    email: "filip.jakovljevic@email.com",
  },
  {
    id: 22,
    firstName: "Helena",
    lastName: "Rukavina",
    phone: "+385 92 404 5050",
    email: "helena.rukavina@email.com",
  },
  {
    id: 23,
    firstName: "Zvonimir",
    lastName: "Ljubić",
    phone: "+385 97 505 6060",
    email: "zvonimir.ljubic@email.com",
  },
  {
    id: 24,
    firstName: "Iva",
    lastName: "Pranjić",
    phone: "+385 99 606 7070",
    email: "iva.pranjic@email.com",
  },
  {
    id: 25,
    firstName: "Mario",
    lastName: "Vuković",
    phone: "+385 91 707 8080",
    email: "mario.vukovic@email.com",
  },
  {
    id: 26,
    firstName: "Diana",
    lastName: "Miljković",
    phone: "+385 98 808 9090",
    email: "diana.miljkovic@email.com",
  },
  {
    id: 27,
    firstName: "Hrvoje",
    lastName: "Barišić",
    phone: "+385 95 909 1010",
    email: "hrvoje.barisic@email.com",
  },
  {
    id: 28,
    firstName: "Nina",
    lastName: "Krpan",
    phone: "+385 92 010 1111",
    email: "nina.krpan@email.com",
  },
  {
    id: 29,
    firstName: "Domagoj",
    lastName: "Glavaš",
    phone: "+385 97 111 1212",
    email: "domagoj.glavas@email.com",
  },
  {
    id: 30,
    firstName: "Paula",
    lastName: "Klarić",
    phone: "+385 99 212 1313",
    email: "paula.klaric@email.com",
  },
  {
    id: 31,
    firstName: "Matej",
    lastName: "Obradović",
    phone: "+385 91 313 1414",
    email: "matej.obradovic@email.com",
  },
  {
    id: 32,
    firstName: "Ema",
    lastName: "Čović",
    phone: "+385 98 414 1515",
    email: "ema.covic@email.com",
  },
].map((t) => ({
  ...t,
  avatar: `${t.firstName[0]}${t.lastName[0]}`,
  id: t.id.toString(),
}));
